<?php


namespace app\user\controller;


use app\BaseController;
use think\exception\HttpResponseException;

class UserBase extends BaseController
{
    public $user = null;
    public function initialize()
    {
        parent::initialize(); // TODO: Change the autogenerated stub
        if (empty($this->isLogin())){
            return $this->redirect(url('/user/login'),302);
        }
    }

    public function isLogin(){
        $this->user = session(config('user.session_user'));
        if (empty($this->user)){
            return false;
        }
        return true;
    }
    public function redirect(...$args){
        throw new HttpResponseException(redirect(...$args));
    }

}